const index = {
	"AJET":{
		"type":"stock",
		"name":"Arcjet Dynamics",
		"loacation":"USA",
		"info":"Arcjet Dynamics",
		"origin":6200},
	"BIO":{
		"type":"stock",
		"name":"Biotech Japan",
		"loacation":"Japan",
		"info":"Biotech Japan",
		"origin":4000},
	"CAA":{
		"type":"stock",
		"name":"Coursing Association of America",
		"loacation":"USA",
		"info":"Coursing Association of America",
		"origin":2200},
	"CBRN":{
		"type":"stock",
		"name":"Cybernetics India",
		"loacation":"India",
		"info":"Cybernetics India",
		"origin":1400},
	"CPPR":{
		"type":"commodity",
		"name":"Copper",
		"info":"Cheap",
		"origin":6000},
	"CRDT":{
		"type":"stock",
		"name":"Credit Services International",
		"loacation":"Israel",
		"info":"Credit Services International",
		"origin":8000},
	"DBNK":{
		"type":"stock",
		"name":"Databanks United",
		"loacation":"China",
		"info":"Databanks United",
		"origin":7600},
	"DMSN":{
		"type":"stock",
		"name":"Dimensions Lifestyle",
		"loacation":"France",
		"info":"Dimensions Lifestyle",
		"origin":5600},
	"DRE":{
		"type":"stock",
		"name":"Deep Resource Extraction",
		"loacation":"Russia",
		"info":"Deep Resource Extraction",
		"origin":4300},
	"DUT":{
		"type":"commodity",
		"name":"Deuterium",
		"info":"Cheap",
		"origin":400},
	"FSIS":{
		"type":"stock",
		"name":"Futanari Sisters",
		"loacation":"Japan",
		"info":"Futanari, Pretty, Skilled, Well-trained, Moderate",
		"origin":7000},
	"GOLD":{
		"type":"commodity",
		"name":"Gold",
		"info":"Expensive",
		"origin":1500},
	"GRI":{
		"type":"stock",
		"name":"Growth Research Institute",
		"loacation":"Germany",
		"info":"Genetically enhanced, Nasty flaws, No training, Expensive",
		"origin":9200},
	"JPTR":{
		"type":"stock",
		"name":"Jupiter Industries",
		"location":"Germany",
		"info":"Jupiter Industries",
		"origin":14000},
	"LEC":{
		"type":"stock",
		"name":"L'École Des Écoles",
		"loacation":"France",
		"info":"Anal expertise, Pretty, Skilled, Strict training, Expensive",
		"origin":12000},
	"LITH":{
		"type":"commodity",
		"name":"Lithium",
		"info":"Expensive",
		"origin":800},
	"MDLR":{
		"type":"stock",
		"name":"Modular Systems",
		"loacation":"Germany",
		"info":"Modular Systems",
		"origin":8700},
	"NTK":{
		"type":"stock",
		"name":"Nanotech Korea",
		"loacation":"Korea",
		"info":"Nanotech Korea",
		"origin":5800},
	"OIL":{
		"type":"commodity",
		"name":"Crude oil",
		"info":"Expensive",
		"origin":60},
	"OPN":{
		"type":"stock",
		"name":"The Open Network",
		"loacation":"Norway",
		"info":"The Open Network",
		"origin":10000},
	"PLAT":{
		"type":"commodity",
		"name":"Platinum",
		"info":"Very expensive",
		"origin":2200},
	"QLNK":{
		"type":"stock",
		"name":"Q-link Global",
		"loacation":"Korea",
		"info":"Q-link Global",
		"origin":11000},
	"REM":{
		"type":"commodity",
		"name":"Rare earth metals",
		"info":"Moderate",
		"origin":80},
	"SLVR":{
		"type":"commodity",
		"name":"Silver",
		"info":"Moderate",
		"origin":15},
	"SOY":{
		"type":"commodity",
		"name":"Soybeans",
		"info":"Very cheap",
		"origin":10},
	"STC":{
		"type":"stock",
		"name":"St. Claver's",
		"loacation":"Spain",
		"info":"Silicone enhanced, Pretty, Skilled, Strict training, Moderate",
		"origin":6300},
	"STRN":{
		"type":"stock",
		"name":"Saturn Incorporated",
		"location":"China",
		"info":"Saturn Incorporated",
		"origin":22300},
	"TGA":{
		"type":"stock",
		"name":"The Gymnasium Academy",
		"loacation":"Russia",
		"info":"Skilled entertainers, Fit, Skilled fighters, Well-trained, Expensive",
		"origin":9100},
	"TSS":{
		"type":"stock",
		"name":"The Slave School",
		"loacation":"USA",
		"info":"Pretty, Skilled, Innocent, No training, Cheap",
		"origin":4600},
	"URNM":{
		"type":"commodity",
		"name":"Uranium",
		"info":"Moderate",
		"origin":25},
	"WHT":{
		"type":"commodity",
		"name":"Wheat",
		"info":"Cheap",
		"origin":200}}
		